<a href="https://colab.research.google.com/github/AlissonValencia/IA_taller1/blob/main/ia_taller1_ejerciciosNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Ejercicios NumPy**



Autor: Alisson Valencia

Fecha: 16/04/2026

----

## **Módulo 1**
---

*Ejercicio 1: Crea una lista con los múltiplos de 7 entre 1 y 100 usando comprehension.*

In [2]:
multiplos_7 = [x for x in range(1, 101) if x % 7 == 0]
print(multiplos_7)

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]


*Ejercicio 2: Dado el diccionario*

In [1]:
datos = {'a':10, 'b':25, 'c':7, 'd':18}

# a) Claves con valor mayor a 12
claves_mayores = [k for k, v in datos.items() if v > 12]
print(claves_mayores)

# b) Nuevo diccionario con valores al cuadrado
dict_cuadrado = {k: v**2 for k, v in datos.items() if v > 12}
print(dict_cuadrado)

['b', 'd']
{'b': 625, 'd': 324}


*Ejercicio 3: Define una función 'resumen(lista)' que retorne un diccionario con:longitud, suma, promedio, mínimo y máximo de la lista.*

In [3]:
def resumen(lista):
    return {
        'longitud': len(lista),
        'suma': sum(lista),
        'promedio': sum(lista) / len(lista),
        'minimo': min(lista),
        'maximo': max(lista)
    }

print(resumen([3, 1, 7, 2, 5]))

{'longitud': 5, 'suma': 18, 'promedio': 3.6, 'minimo': 1, 'maximo': 7}


*Ejercicio 4: Usa map() para aplicar la función potencia(x, 3) a la lista [1,2,3,4,5].*

In [ ]:
def potencia(x, exp=3):
    return x ** exp

lista = [1, 2, 3, 4, 5]
resultado = list(map(lambda x: potencia(x), lista))
print(resultado)

[1, 8, 27, 64, 125]


## **Módulo 2**
---

*Ejercicio 1: Crea los siguientes arrays y verifica sus atributos (shape, dtype, ndim):*


In [ ]:
import numpy as np

In [6]:
import numpy as np

# a) Vector con enteros del 1 al 20
vector = np.arange(1, 21)
print('Vector:', vector)
print('shape:', vector.shape, 'dtype:', vector.dtype, 'ndim:', vector.ndim)

# b) Matriz de ceros 5x3
matriz_ceros = np.zeros((5, 3))
print('Ceros shape:', matriz_ceros.shape, 'dtype:', matriz_ceros.dtype)

# c) 10 puntos entre -1 y 1
puntos = np.linspace(-1, 1, 10)
print('Linspace:', puntos)
print('shape:', puntos.shape, 'dtype:', puntos.dtype)

Vector: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
shape: (20,) dtype: int64 ndim: 1
Ceros shape: (5, 3) dtype: float64
Linspace: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
shape: (10,) dtype: float64


*Ejercicio* 2: Con np.random.seed(99) crea una matriz 4×4 de enteros entre 0 y 50.

In [7]:
#Imprime: shape, dtype, tamaño en bytes (nbytes) y el elemento [2,3].
np.random.seed(99)
matriz = np.random.randint(0, 51, size=(4, 4))
print(matriz)
print('shape:', matriz.shape)
print('dtype:', matriz.dtype)
print('nbytes:', matriz.nbytes)
print('elemento [2,3]:', matriz[2, 3])

[[ 1 35 40  9]
 [40 18  4  5]
 [ 1 23 35 49]
 [ 1 48 29 38]]
shape: (4, 4)
dtype: int64
nbytes: 128
elemento [2,3]: 49


*Ejercicio 3: ¿Cuál es la diferencia de dtype entre np.array([1,2,3]) y np.array([1.0,2.0,3.0])? Verifica con código.*

In [8]:
enteros = np.array([1, 2, 3])
flotantes = np.array([1.0, 2.0, 3.0])

print('Enteros dtype:', enteros.dtype)
print('Flotantes dtype:', flotantes.dtype)

Enteros dtype: int64
Flotantes dtype: float64


*Ejercicio* 4: Crea una matriz identidad 5×5 y verifica que la suma de su diagonal es igual a 5 (usa np.trace())

In [9]:
identidad = np.eye(5)
print(identidad)
print('Suma diagonal (trace):', np.trace(identidad))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Suma diagonal (trace): 5.0


## **Módulo 3**
---

In [ ]:
import numpy as np

*Ejercicio 1: Dado A = np.arange(1, 26).reshape(5, 5)*

In [10]:
A = np.arange(1, 26).reshape(5, 5)
print(A)

# a) Sub-matriz: 3 ultimas filas, 3 primeras columnas
sub = A[-3:, :3]
print('Sub-matriz:\n', sub)

# b) Segunda columna completa
col2 = A[:, 1]
print('Segunda columna:', col2)

# c) Elementos de las esquinas
esquinas = A[[0, 0, -1, -1], [0, -1, 0, -1]]
print('Esquinas:', esquinas)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Sub-matriz:
 [[11 12 13]
 [16 17 18]
 [21 22 23]]
Segunda columna: [ 2  7 12 17 22]
Esquinas: [ 1  5 21 25]


*Ejercicio 2: Con la misma matriz A: texto en cursiva*

In [11]:
# a) Mascara para valores mayores a 12
mascara = A > 12
print('Mascara:\n', mascara)

# b) Reemplazar por -1 en copia
B = A.copy()
B[mascara] = -1
print('Copia con -1:\n', B)

# c) np.where: impares por 0, pares se mantienen
C = np.where(A % 2 == 1, 0, A)
print('Impares a 0:\n', C)

Mascara:
 [[False False False False False]
 [False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
Copia con -1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
Impares a 0:
 [[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]


*Ejercicio 3: Crea un vector de 24 elementos con arange(24).*
*Reorganízalo en: (a) matriz 6×4, (b) tensor 2×3×4, (c) vector fila 1×24.*

In [12]:
v = np.arange(24)
print('Original:', v.shape)

# a) Matriz 6x4
m64 = v.reshape(6, 4)
print('6x4:', m64.shape)

# b) Tensor 2x3x4
t234 = v.reshape(2, 3, 4)
print('2x3x4:', t234.shape)

# c) Vector fila 1x24
fila = v.reshape(1, 24)
print('1x24:', fila.shape)

Original: (24,)
6x4: (6, 4)
2x3x4: (2, 3, 4)
1x24: (1, 24)


*Ejercicio 4: Demuestra la diferencia vista vs. copia: modifica un elemento en un slice y verifica que el array original también cambia.*

In [13]:
arr = np.arange(10)
print('Original:', arr)

# Slice es vista
vista = arr[2:5]
vista[0] = 999
print('Desde modificada:', arr)
print('El original tambien cambio porque el slice es una vista')

Original: [0 1 2 3 4 5 6 7 8 9]
Desde modificada: [  0   1 999   3   4   5   6   7   8   9]
El original tambien cambio porque el slice es una vista


## **Módulo 4**
---

*Ejercicio 1: Crea una matriz 5×4 de enteros aleatorios entre 1 y 100 (seed=7).*

In [14]:
#Fórmula: (x - min_col) / (max_col - min_col)
np.random.seed(7)
M = np.random.randint(1, 101, size=(5, 4))
print(M)

# a) Media, max, min por columna
print('Media columnas:', M.mean(axis=0))
print('Max columnas:', M.max(axis=0))
print('Min columnas:', M.min(axis=0))

# b) Suma acumulada primera fila
print('Suma acumulada fila 0:', np.cumsum(M[0]))

# c) Normalizar columnas entre 0 y 1
min_col = M.min(axis=0)
max_col = M.max(axis=0)
normalizada = (M - min_col) / (max_col - min_col)
print('Normalizada:\n', normalizada)

[[48 69 26 68]
 [84 24 93 58]
 [15 24 73 90]
 [43 91  9 40]
 [69 49  8 45]]
Media columnas: [51.8 51.4 41.8 60.2]
Max columnas: [84 91 93 90]
Min columnas: [15 24  8 40]
Suma acumulada fila 0: [ 48 117 143 211]
Normalizada:
 [[0.47826087 0.67164179 0.21176471 0.56      ]
 [1.         0.         1.         0.36      ]
 [0.         0.         0.76470588 1.        ]
 [0.4057971  1.         0.01176471 0.        ]
 [0.7826087  0.37313433 0.         0.1       ]]


*Ejercicio 2: Usando broadcasting:*

In [15]:
# a) Vector fila y vector columna
fila = np.array([1, 2, 3, 4])
columna = np.array([[10], [20], [30]])

print('Fila shape:', fila.shape)
print('Columna shape:', columna.shape)

# b) Suma
resultado = columna + fila
print('Resultado:\n', resultado)
print('Resultado shape:', resultado.shape)
print('El shape es 3x4: se expande la fila a 3 filas y la columna a 4 columnas')

Fila shape: (4,)
Columna shape: (3, 1)
Resultado:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
Resultado shape: (3, 4)
El shape es 3x4: se expande la fila a 3 filas y la columna a 4 columnas


*Ejercicio 3: Con el array de notas y nombres del ejemplo de argsort:*

In [16]:
nombres = np.array(['Alisson','Celeste','Bryan','Jorge','Paulina','Damian'])
notas = np.array([75, 92, 88, 61, 95, 78])

# a) Cuantos tienen nota mayor al promedio
promedio = notas.mean()
mayores_promedio = notas > promedio
cantidad = np.sum(mayores_promedio)
print('Promedio:', promedio)
print('Cantidad mayor al promedio:', cantidad)

# b) Nombres de esos estudiantes
print('Nombres:', nombres[mayores_promedio])

Promedio: 81.5
Cantidad mayor al promedio: 3
Nombres: ['Celeste' 'Bryan' 'Paulina']


*Ejercicio 4: Crea dos matrices 3×4 y concaténalas vertical y horizontalmente.*

In [17]:
#Luego divide el resultado vertical en 3 partes iguales con vsplit.
A = np.arange(12).reshape(3, 4)
B = np.arange(12, 24).reshape(3, 4)

# Concatenar vertical
vertical = np.vstack((A, B))
print('Vertical 6x4:\n', vertical)

# Concatenar horizontal
horizontal = np.hstack((A, B))
print('Horizontal 3x8:\n', horizontal)

# Dividir vertical en 3 partes
partes = np.vsplit(vertical, 3)
print('Partes:', len(partes))
for i, p in enumerate(partes):
    print(f'Parte {i} shape:', p.shape)

Vertical 6x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Horizontal 3x8:
 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
Partes: 3
Parte 0 shape: (2, 4)
Parte 1 shape: (2, 4)
Parte 2 shape: (2, 4)
